version: 0.2
env:
  variables:
    APP_NAME: "hello-graphql"
phases:
  install:
    runtime-versions:
      nodejs: 16.x
    commands:
      - echo install process started
      - npm install
  post_build:
    commands:
      - echo build process finished, we should upload to S3 now
      - cd dist/$APP_NAME
      - ls -la
      - aws s3 sync . s3://codepipeline-ap-southeast-1-376047783232 --delete