version: 0.2
env:
  variables:
    APP_NAME: "hello-graphql"
phases:
  post_build:
    commands:
      - echo build process finished, we should upload to S3 now
      - ls -la
      - aws s3 sync . s3://codepipeline-ap-southeast-1-376047783232 --delete